apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: collector-service
  template:
    metadata:
      labels:
        app: collector-service
    spec:
      containers:
      - name: collector-service
        image: gcr.io/univiecca1/collector-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8088